### ISSUE TITLE
Maybe add a readme? :)

### ISSUE THREAD

**Issue by kinetiq** [Aldaviva/ThrottleDebounce#2]
Some examples would really help with adoption. 

*air horn noise*

**Comment by Aldaviva** [comment]
Sorry I missed this issue when it was filed. A few days before that, I actually wrote a [readme for the 2.0 branch](https://github.com/Aldaviva/ThrottleDebounce/blob/2.0/Readme.md), but then somehow forgot to merge it into the mainline branch and upload it to NuGet. I will try to get that sorted out soon.

**Comment by Aldaviva** [comment]
Finally released [2.0.0](https://www.nuget.org/packages/ThrottleDebounce/2.0.0) which includes a [Readme](https://github.com/Aldaviva/ThrottleDebounce/tree/2.0.0#readme).
